services:
  - type: web
    name: praticante-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:application --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: praticante_db
          property: connectionString
