services:
  - type: web
    name: praticante-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.app:application"
    envVars:
      - key: FLASK_SECRET_KEY
        value: "sua-chave-secreta"
      - key: DATABASE_URL
        value: "URL-do-seu-banco-postgres"
