services:
  - type: web
    name: praticante-app
    runtime: python
    buildCommand: |
      chmod +x .env.sh
      ./.env.sh
      pip install -r requirements.txt
    startCommand: gunicorn app:application
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: praticante_db
          property: connectionString
